### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by arielcostas** [kevinboone/jgemini#2]
Hi there, looking around the net for a Gemini client implemented in Java (especially the `gemini://` protocol implementation and TLS) I found this repository and [the article at kevinboone.me](https://kevinboone.me/jgemini.html).

However, I can't seem to find a LICENSE or similar to be able to learn from the source code/modify it. Could you please consider adding a license to this repo? GitHub maintains [Choose a License](https://choosealicense.com/) providing guidance on how to choose a license for your programs.

Edit: I see in some comments on the source (like `src/main/java/me/kevinboone/jgemini/MarkdownConverter.java`) it's under the GPL version 3, so I assume that's the license

**Comment by kevinboone** [comment]
Hi. Your assumption is correct. I have added a COPYING file to clarify the situation. I hope you find the program useful.
